import fs from 'node:fs';
import assert from 'node:assert/strict';
const read = rel => fs.readFileSync(new URL('../../' + rel, import.meta.url), 'utf8');

const page = read('includes/Admin/Pages/CouponsPage.php');
const repo = read('includes/Infrastructure/Repositories/CouponRepository.php');
const service = read('includes/Application/Services/MarketingEmailService.php');

assert.match(page, /\$coupons = \$this->repo->get_marketing_templates\(\)/);
assert.match(repo, /public function get_marketing_templates\(\)/);
assert.match(repo, /generated_ids/);
assert.match(repo, /payload\['coupon'\]\['id'\]/);
assert.match(repo, /personal coupon/);
assert.match(repo, /marketing campaign/);

assert.match(service, /Personal coupon generated by marketing campaign/);
assert.match(service, /'usage_limit' => 1/);
assert.match(service, /'usage_limit_per_email' => 1/);
assert.match(repo, /public function get_by_code\(string \$code\)/);

console.log('generated personal coupons stay redeemable but are hidden from the main Coupons list: ok');
