<?php

declare(strict_types=1);

namespace Slotera\Application\Services;

if (!defined('ABSPATH')) { exit; }

final class BookingAccessTokenService
{
    private const CODE_TTL = 1800;
    private const SESSION_TTL = 1800;
    private const CODE_PREFIX = 'sltr_bac_';
    private const SESSION_PREFIX = 'sltr_bas_';
    private const COOKIE_PREFIX = 'sltr_booking_access_';

    public function issue_code(array $booking): string
    {
        $booking_id = absint($booking['id'] ?? 0);
        $binding = $this->legacy_token_for_booking($booking);
        if ($booking_id <= 0 || $binding === '') { return ''; }

        try {
            $code = bin2hex(random_bytes(32));
        } catch (\Throwable $e) {
            $code = wp_generate_password(64, false, false);
        }
        set_transient(self::CODE_PREFIX . hash('sha256', $code), [
            'booking_id' => $booking_id,
            'binding' => $binding,
        ], self::CODE_TTL);
        return $code;
    }

    /** @deprecated Use issue_code(). */
    public function token_for_booking(array $booking): string
    {
        return $this->issue_code($booking);
    }

    public function exchange_code(array $booking, string $code): bool
    {
        $code = sanitize_text_field($code);
        if ($code === '') { return false; }
        $key = self::CODE_PREFIX . hash('sha256', $code);
        $claim = '_sltr_bac_claim_' . hash('sha256', $code);
        // add_option() is a database-level unique insert. It serializes
        // concurrent exchanges before the non-atomic transient read/delete.
        if (!add_option($claim, time(), '', false)) { return false; }
        try {
            $record = get_transient($key);
            delete_transient($key);
            if (!is_array($record)) { return false; }

            $booking_id = absint($booking['id'] ?? 0);
            $expected_binding = $this->legacy_token_for_booking($booking);
            if ($booking_id <= 0 || absint($record['booking_id'] ?? 0) !== $booking_id || $expected_binding === '' || !hash_equals($expected_binding, (string) ($record['binding'] ?? ''))) {
                return false;
            }
            return $this->establish_session($booking);
        } finally {
            // Once the transient is deleted a later exchange fails closed; the
            // short-lived claim only needs to cover concurrent requests.
            delete_option($claim);
        }
    }

    public function exchange_legacy_token(array $booking, string $token): bool
    {
        if (!$this->verify_legacy($booking, $token)) { return false; }
        $marker = '_sltr_legacy_access_used_' . hash('sha256', sanitize_text_field($token));
        if (!add_option($marker, time(), '', false)) { return false; }
        if ($this->establish_session($booking)) { return true; }
        delete_option($marker);
        return false;
    }

    public function has_session(array $booking): bool
    {
        $booking_id = absint($booking['id'] ?? 0);
        if ($booking_id <= 0) { return false; }
        $cookie = sanitize_text_field((string) ($_COOKIE[$this->cookie_name($booking_id)] ?? ''));
        if ($cookie === '') { return false; }
        $record = get_transient(self::SESSION_PREFIX . hash('sha256', $cookie));
        if (!is_array($record) || absint($record['booking_id'] ?? 0) !== $booking_id) { return false; }
        $binding = $this->legacy_token_for_booking($booking);
        return $binding !== '' && hash_equals($binding, (string) ($record['binding'] ?? ''));
    }

    /** @deprecated Only retained to exchange links generated by older releases. */
    public function verify(array $booking, string $token): bool
    {
        return $this->verify_legacy($booking, $token);
    }

    private function establish_session(array $booking): bool
    {
        if (headers_sent()) { return false; }
        $booking_id = absint($booking['id'] ?? 0);
        $binding = $this->legacy_token_for_booking($booking);
        if ($booking_id <= 0 || $binding === '') { return false; }
        try {
            $session = bin2hex(random_bytes(32));
        } catch (\Throwable $e) {
            $session = wp_generate_password(64, false, false);
        }
        set_transient(self::SESSION_PREFIX . hash('sha256', $session), ['booking_id' => $booking_id, 'binding' => $binding], self::SESSION_TTL);
        setcookie($this->cookie_name($booking_id), $session, [
            'expires' => time() + self::SESSION_TTL,
            'path' => COOKIEPATH ?: '/',
            'secure' => $this->should_secure_cookie(),
            'httponly' => true,
            'samesite' => 'Lax',
        ]);
        $_COOKIE[$this->cookie_name($booking_id)] = $session;
        return true;
    }

    private function should_secure_cookie(): bool
    {
        if (is_ssl()) {
            return true;
        }
        return strtolower((string) wp_parse_url(home_url('/'), PHP_URL_SCHEME)) === 'https';
    }

    private function verify_legacy(array $booking, string $token): bool
    {
        $token = sanitize_text_field($token);
        $expected = $this->legacy_token_for_booking($booking);
        return $token !== '' && $expected !== '' && hash_equals($expected, $token);
    }

    private function legacy_token_for_booking(array $booking): string
    {
        $booking_id = absint($booking['id'] ?? 0);
        if ($booking_id <= 0) { return ''; }
        $material = implode('|', [
            $booking_id,
            sanitize_text_field((string) ($booking['cancellation_token'] ?? '')),
            sanitize_text_field((string) ($booking['reschedule_token'] ?? '')),
            sanitize_text_field((string) ($booking['created_at'] ?? '')),
        ]);
        return hash_hmac('sha256', $material, wp_salt('auth'));
    }

    private function cookie_name(int $booking_id): string
    {
        return self::COOKIE_PREFIX . $booking_id;
    }
}
