<?php

declare(strict_types=1);

namespace Slotera\Application\Services;

use Slotera\Infrastructure\Repositories\SettingsRepository;

if (!defined('ABSPATH')) {
    exit;
}

final class RobotsTxtService
{
    public function path(): string
    {
        return trailingslashit((string) ABSPATH) . 'robots.txt';
    }

    public function exists(): bool
    {
        return is_file($this->path());
    }

    public function is_writable_target(): bool
    {
        $path = $this->path();
        if (is_file($path)) {
            return is_writable($path);
        }

        $dir = dirname($path);
        return is_dir($dir) && is_writable($dir);
    }

    public function current_content(): string
    {
        if (!$this->exists() || !is_readable($this->path())) {
            return '';
        }

        $content = file_get_contents($this->path());
        return is_string($content) ? $content : '';
    }

    public function default_content(): string
    {
        $settings = (new SettingsRepository())->all();
        $smart_enabled = !empty($settings['seo_robots_smart_builder_enabled']);

        $lines = [
            '# robots.txt generated by Slotera Booking',
            'User-agent: *',
            'Disallow: /wp-admin/',
            'Allow: /wp-admin/admin-ajax.php',
        ];

        if ($smart_enabled) {
            $this->append_search_rules($lines, $settings);
            $this->append_slotera_technical_page_rules($lines, $settings);
            $this->append_tracking_parameter_rules($lines, $settings);
            $this->append_attachment_rules($lines, $settings);
        }

        $lines[] = '';
        $this->append_sitemap_rules($lines, $settings);
        $this->append_custom_rules($lines, (string) ($settings['seo_robots_custom_rules'] ?? ''));

        return implode("
", $this->unique_lines($lines));
    }

    /** @param array<int, string> $lines @param array<string, mixed> $settings */
    private function append_search_rules(array &$lines, array $settings): void
    {
        if (empty($settings['seo_robots_block_wp_search'])) {
            return;
        }

        $lines[] = '';
        $lines[] = '# WordPress search URLs';
        $lines[] = 'Disallow: /?s=';
        $lines[] = 'Disallow: /search/';
    }

    /** @param array<int, string> $lines @param array<string, mixed> $settings */
    private function append_slotera_technical_page_rules(array &$lines, array $settings): void
    {
        if (empty($settings['seo_robots_block_slotera_technical'])) {
            return;
        }

        $repo = new SettingsRepository();
        $keys = ['checkout', 'thank_you', 'login', 'account'];
        $paths = [];
        foreach ($keys as $key) {
            $page_id = $repo->get_page_id($key);
            if ($page_id <= 0) {
                continue;
            }
            $path = $this->path_from_url((string) get_permalink($page_id));
            if ($path !== '') {
                $paths[] = $path;
            }
        }

        // Token/action endpoints are intentionally non-indexable technical URLs.
        foreach (['/booking-success/', '/booking-cancel/', '/cancel/', '/reschedule/', '/account/', '/checkout/', '/login/'] as $fallback) {
            $paths[] = $fallback;
        }

        $paths = array_values(array_unique(array_filter($paths)));
        if (empty($paths)) {
            return;
        }

        $lines[] = '';
        $lines[] = '# Slotera technical pages';
        foreach ($paths as $path) {
            $lines[] = 'Disallow: ' . $path;
        }
    }

    /** @param array<int, string> $lines @param array<string, mixed> $settings */
    private function append_tracking_parameter_rules(array &$lines, array $settings): void
    {
        if (empty($settings['seo_robots_block_tracking_params'])) {
            return;
        }

        $lines[] = '';
        $lines[] = '# Tracking and filter parameters';
        foreach (['/*?utm_', '/*?fbclid=', '/*?gclid=', '/*?msclkid=', '/*?orderby=', '/*?sort=', '/*?filter='] as $rule) {
            $lines[] = 'Disallow: ' . $rule;
        }
    }

    /** @param array<int, string> $lines @param array<string, mixed> $settings */
    private function append_attachment_rules(array &$lines, array $settings): void
    {
        if (empty($settings['seo_robots_block_attachment_pages'])) {
            return;
        }

        $lines[] = '';
        $lines[] = '# WordPress attachment pages';
        $lines[] = 'Disallow: /attachment/';
    }

    /** @param array<int, string> $lines @param array<string, mixed> $settings */
    private function append_sitemap_rules(array &$lines, array $settings): void
    {
        if (empty($settings['seo_robots_add_sitemap'])) {
            return;
        }

        $urls = [];
        $external_active = class_exists('\Slotera\Application\Services\SEOService') && count((new SEOService())->detected_external_plugins()) > 0;
        if ($external_active) {
            $urls[] = home_url('/sitemap_index.xml');
        } else {
            $urls[] = home_url('/wp-sitemap.xml');
            if (!empty($settings['seo_sitemap_enabled'])) {
                $urls[] = home_url('/slotera-sitemap.xml');
            }
        }

        $urls = array_values(array_unique(array_map('esc_url_raw', $urls)));
        if (empty($urls)) {
            return;
        }

        $lines[] = '# Sitemaps';
        foreach ($urls as $url) {
            $lines[] = 'Sitemap: ' . $url;
        }
        $lines[] = '';
    }

    /** @param array<int, string> $lines */
    private function append_custom_rules(array &$lines, string $custom): void
    {
        $custom = $this->sanitize_content($custom);
        if ($custom === '') {
            return;
        }

        $lines[] = '# Custom rules';
        foreach (explode("
", trim($custom)) as $line) {
            $line = trim($line);
            if ($line !== '') {
                $lines[] = $line;
            }
        }
        $lines[] = '';
    }

    private function path_from_url(string $url): string
    {
        $path = (string) wp_parse_url($url, PHP_URL_PATH);
        if ($path === '') {
            return '';
        }
        return trailingslashit('/' . ltrim($path, '/'));
    }

    /** @param array<int, string> $lines @return array<int, string> */
    private function unique_lines(array $lines): array
    {
        $seen = [];
        $out = [];
        foreach ($lines as $line) {
            $key = trim($line);
            if ($key !== '' && isset($seen[$key])) {
                continue;
            }
            if ($key !== '') {
                $seen[$key] = true;
            }
            $out[] = $line;
        }

        while (!empty($out) && trim((string) end($out)) === '') {
            array_pop($out);
        }
        $out[] = '';
        return $out;
    }

    public function sanitize_content(string $content): string
    {
        $content = str_replace(["\r\n", "\r"], "\n", $content);
        $content = preg_replace('/[^\P{C}
	]/u', '', $content);
        if (!is_string($content)) {
            $content = '';
        }

        $content = trim($content);
        if ($content === '') {
            return '';
        }

        return $content . "
";
    }

    public function backup_existing(): bool
    {
        if (!$this->exists()) {
            return true;
        }

        $path = $this->path();
        if (!is_readable($path) || !is_writable(dirname($path))) {
            return false;
        }

        $backup = dirname($path) . '/robots.txt.slotera-backup-' . gmdate('Ymd-His') . '.bak';
        if (is_file($backup)) {
            $backup = dirname($path) . '/robots.txt.slotera-backup-' . gmdate('Ymd-His') . '-' . wp_generate_password(6, false, false) . '.bak';
        }

        return copy($path, $backup);
    }

    public function write(string $content): bool
    {
        if (!$this->is_writable_target()) {
            return false;
        }

        $bytes = file_put_contents($this->path(), $this->sanitize_content($content), LOCK_EX);
        return is_int($bytes) && $bytes >= 0;
    }
}
