<?php
declare(strict_types=1);

namespace Slotera\Infrastructure\Repositories;

use Slotera\Core\Database;

if (!defined('ABSPATH')) { exit; }

final class CouponRepository
{
    public function get_all(): array
    {
        global $wpdb;
        $table = Database::coupons_table();
        return $wpdb->get_results("SELECT * FROM {$table} ORDER BY created_at DESC", ARRAY_A) ?: [];
    }


    /**
     * Return coupons that may be used as reusable marketing templates.
     * Recipient-specific coupons generated by previous campaigns must never
     * appear as a source promotion for a new campaign or automation.
     */
    public function get_marketing_templates(): array
    {
        global $wpdb;

        $generated_ids = [];
        $logs_table = Database::marketing_logs_table();
        $payloads = $wpdb->get_col(
            "SELECT payload_json FROM {$logs_table} WHERE payload_json IS NOT NULL AND payload_json <> ''"
        ) ?: [];
        foreach ($payloads as $payload_json) {
            $payload = json_decode((string) $payload_json, true);
            if (!is_array($payload) || empty($payload['coupon']) || !is_array($payload['coupon'])) { continue; }
            $coupon_id = absint($payload['coupon']['id'] ?? 0);
            if ($coupon_id > 0) { $generated_ids[$coupon_id] = true; }
        }

        return array_values(array_filter($this->get_all(), static function (array $coupon) use ($generated_ids): bool {
            $coupon_id = absint($coupon['id'] ?? 0);
            if ($coupon_id > 0 && isset($generated_ids[$coupon_id])) { return false; }

            // Fallback for old or minimized logs where the coupon payload may
            // no longer be present. Match broad, stable campaign markers.
            $description_raw = trim(wp_strip_all_tags((string) ($coupon['description'] ?? '')));
            $description = strtolower($description_raw);
            if ($description === '') { return true; }

            if (str_contains($description, '[slotera:generated_personal_coupon]')) { return false; }
            if (str_contains($description, '[slotera:automation_offer_template]')) { return false; }

            $has_campaign_marker = str_contains($description, 'marketing campaign')
                || str_contains($description, 'маркетинговой кампани')
                || str_contains($description, 'marketing кампания')
                || str_contains($description, 'campagne marketing')
                || str_contains($description, 'marketingkampagne')
                || str_contains($description, 'turunduskampaani');
            $has_personal_marker = str_contains($description, 'personal coupon')
                || str_contains($description, 'персональный купон')
                || str_contains($description, 'заsonal купон')
                || str_contains($description, 'coupon personnel')
                || str_contains($description, 'persönlicher gutschein')
                || str_contains($description, 'personaalne kupong');
            if ($has_campaign_marker && $has_personal_marker) { return false; }

            // Legacy generated coupons can outlive a deleted campaign/log. Their
            // one-use shape, random code suffix and recipient email form a stable
            // fallback that does not depend on sending history or UI locale.
            $legacy_one_use = (int) ($coupon['usage_limit'] ?? 0) === 1 && (int) ($coupon['usage_limit_per_email'] ?? 0) === 1;
            $legacy_code = strtoupper((string) ($coupon['code'] ?? ''));
            $legacy_suffix = (bool) preg_match('/^.+-[A-Z0-9]{6,8}$/', $legacy_code);
            $legacy_recipient = (bool) preg_match('/[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}/i', $description_raw);
            if ($legacy_one_use && $legacy_suffix && $legacy_recipient) { return false; }

            return true;
        }));
    }

    public function get_by_id(int $id): ?array
    {
        global $wpdb;
        $table = Database::coupons_table();
        $row = $wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE id=%d LIMIT 1", $id), ARRAY_A);
        return $row ?: null;
    }

    public function get_by_code(string $code): ?array
    {
        global $wpdb;
        $table = Database::coupons_table();
        $code = $this->normalize_code($code);
        if ($code === '') { return null; }
        $row = $wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE code=%s LIMIT 1", $code), ARRAY_A);
        return $row ?: null;
    }

    public function create(array $data): int
    {
        global $wpdb;
        $table = Database::coupons_table();
        $now = current_time('mysql');
        $normalized = $this->normalize($data);
        if ($normalized['code'] === '') { return 0; }
        $ok = $wpdb->insert($table, array_merge($normalized, ['created_at' => $now, 'updated_at' => $now]));
        $id = $ok ? (int) $wpdb->insert_id : 0; if ($id > 0) { do_action('sltr_data_changed', 'coupon_created', ['package_ids' => array_filter(array_map('absint', explode(',', (string) ($normalized['package_ids'] ?? ''))))]); } return $id;
    }

    public function update(int $id, array $data): bool
    {
        global $wpdb;
        $table = Database::coupons_table();
        $current = $this->get_by_id($id);
        if (!$current) { return false; }
        $normalized = $this->normalize(array_merge($current, $data));
        $normalized['updated_at'] = current_time('mysql');
        $updated = $wpdb->update($table, $normalized, ['id' => $id]) !== false; if ($updated) { do_action('sltr_data_changed', 'coupon_updated', ['package_ids' => array_filter(array_map('absint', explode(',', (string) ($normalized['package_ids'] ?? ''))))]); } return $updated;
    }

    public function delete(int $id): bool
    {
        global $wpdb;
        $deleted = $wpdb->delete(Database::coupons_table(), ['id' => $id], ['%d']) !== false; if ($deleted) { do_action('sltr_data_changed', 'coupon_deleted'); } return $deleted;
    }

    public function increment_usage(int $id): bool
    {
        global $wpdb;
        $table = Database::coupons_table();
        return $wpdb->query($wpdb->prepare("UPDATE {$table} SET used_count=used_count+1, updated_at=%s WHERE id=%d", current_time('mysql'), $id)) !== false;
    }

    public function normalize_code(string $code): string
    {
        $code = strtoupper(sanitize_text_field($code));
        $code = preg_replace('/[^A-Z0-9_\-]/', '', $code) ?: '';
        return substr($code, 0, 50);
    }

    private function normalize(array $data): array
    {
        $type = sanitize_key((string) ($data['discount_type'] ?? 'percent'));
        if (!in_array($type, ['percent', 'fixed'], true)) { $type = 'percent'; }
        $package_ids = array_filter(array_map('absint', preg_split('/[\s,]+/', (string) ($data['package_ids'] ?? '')) ?: []));
        $package_ids = array_values(array_unique($package_ids));
        return [
            'code' => $this->normalize_code((string) ($data['code'] ?? '')),
            'description' => sanitize_textarea_field((string) ($data['description'] ?? '')),
            'discount_type' => $type,
            'discount_value' => max(0, (float) ($data['discount_value'] ?? 0)),
            'usage_limit' => max(0, (int) ($data['usage_limit'] ?? 0)),
            'usage_limit_per_email' => max(0, (int) ($data['usage_limit_per_email'] ?? 0)),
            'used_count' => max(0, (int) ($data['used_count'] ?? 0)),
            'expires_at' => sanitize_text_field((string) ($data['expires_at'] ?? '')) ?: null,
            'package_ids' => implode(',', $package_ids),
            'min_amount' => max(0, (float) ($data['min_amount'] ?? 0)),
            'is_active' => !empty($data['is_active']) ? 1 : 0,
        ];
    }
}
