<?php
declare(strict_types=1);
namespace Slotera\Core;
if (!defined('ABSPATH')) { exit; }

/**
 * Owns database schema creation so the Database facade only exposes table names
 * and a small compatibility entry point.
 */
final class DatabaseSchemaInstaller
{
    public static function install(): void {
        self::create_tables();
    }

    public static function create_tables(): void {
        global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $charset=$wpdb->get_charset_collate();
        $categories=Database::categories_table(); $locations=Database::locations_table(); $package_locations=Database::package_locations_table(); $packages=Database::packages_table(); $events=Database::events_table(); $hours=Database::working_hours_table(); $bookings=Database::bookings_table(); $log=Database::activity_log_table(); $history=Database::booking_history_table(); $webhooks=Database::webhook_events_table(); $email_queue=Database::email_queue_table(); $coupons=Database::coupons_table(); $marketing_campaigns=Database::marketing_campaigns_table(); $marketing_logs=Database::marketing_logs_table(); $rate_limits=Database::rate_limits_table(); $rest_hmac_nonces=Database::rest_hmac_nonces_table(); $visitor_events=Database::visitor_events_table(); $outgoing_endpoints=Database::outgoing_webhook_endpoints_table(); $outgoing_deliveries=Database::outgoing_webhook_deliveries_table(); $payment_transactions=Database::payment_transactions_table(); $payment_invoices=Database::payment_invoices_table();
        $sql_categories="CREATE TABLE {$categories} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            name VARCHAR(191) NOT NULL,
            slug VARCHAR(191) NOT NULL,
            description LONGTEXT NULL,
            title_font_family VARCHAR(160) NOT NULL DEFAULT '',
            title_font_size INT UNSIGNED NOT NULL DEFAULT 24,
            seo_title VARCHAR(255) NOT NULL DEFAULT '',
            seo_site_title_position VARCHAR(10) NOT NULL DEFAULT 'right',
            seo_description TEXT NULL,
            seo_og_title VARCHAR(255) NOT NULL DEFAULT '',
            seo_og_description TEXT NULL,
            seo_og_image VARCHAR(500) NOT NULL DEFAULT '',
            seo_canonical VARCHAR(500) NOT NULL DEFAULT '',
            seo_redirect_301 VARCHAR(500) NOT NULL DEFAULT '',
            seo_robots VARCHAR(30) NOT NULL DEFAULT 'index,follow',
            seo_i18n_json LONGTEXT NULL,
            sort_order INT NOT NULL DEFAULT 0,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            page_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY slug (slug),
            KEY is_active (is_active),
            KEY sort_order (sort_order),
            KEY page_id (page_id)
        ) {$charset};";
        $sql_locations="CREATE TABLE {$locations} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            name VARCHAR(191) NOT NULL,
            slug VARCHAR(191) NOT NULL,
            description LONGTEXT NULL,
            intro_content LONGTEXT NULL,
            faq_json LONGTEXT NULL,
            sort_order INT NOT NULL DEFAULT 0,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY slug (slug),
            KEY is_active (is_active),
            KEY sort_order (sort_order)
        ) {$charset};";
        $sql_package_locations="CREATE TABLE {$package_locations} (
            package_id BIGINT UNSIGNED NOT NULL,
            location_id BIGINT UNSIGNED NOT NULL,
            intro_override LONGTEXT NULL,
            faq_override_json LONGTEXT NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (package_id, location_id),
            KEY location_id (location_id),
            KEY package_id (package_id)
        ) {$charset};";
        $sql_packages="CREATE TABLE {$packages} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            category_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            title VARCHAR(191) NOT NULL,
            slug VARCHAR(191) NOT NULL,
            description LONGTEXT NULL,
            title_font_family VARCHAR(160) NOT NULL DEFAULT '',
            title_font_size INT UNSIGNED NOT NULL DEFAULT 24,
            seo_title VARCHAR(255) NOT NULL DEFAULT '',
            seo_site_title_position VARCHAR(10) NOT NULL DEFAULT 'right',
            seo_description TEXT NULL,
            seo_og_title VARCHAR(255) NOT NULL DEFAULT '',
            seo_og_description TEXT NULL,
            seo_og_image VARCHAR(500) NOT NULL DEFAULT '',
            seo_canonical VARCHAR(500) NOT NULL DEFAULT '',
            seo_redirect_301 VARCHAR(500) NOT NULL DEFAULT '',
            seo_robots VARCHAR(30) NOT NULL DEFAULT 'index,follow',
            seo_i18n_json LONGTEXT NULL,
            solo_top_content LONGTEXT NULL,
            show_solo_top_content TINYINT(1) NOT NULL DEFAULT 0,
            solo_content LONGTEXT NULL,
            solo_down_content LONGTEXT NULL,
            show_solo_down_content TINYINT(1) NOT NULL DEFAULT 0,
            show_more_info TINYINT(1) NOT NULL DEFAULT 1,
            solo_page_enabled TINYINT(1) NOT NULL DEFAULT 1,
            card_image_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            booking_card_image_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            card_image_focus VARCHAR(15) NOT NULL DEFAULT '50,50',
            booking_card_image_focus VARCHAR(15) NOT NULL DEFAULT '50,50',
            solo_media_json LONGTEXT NULL,
            solo_contact_image_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            solo_contact_map TEXT NULL,
            solo_contact_details_json LONGTEXT NULL,
            slider_image_ids TEXT NULL,
            slider_image_focus_json LONGTEXT NULL,
            slider_speed INT UNSIGNED NOT NULL DEFAULT 4000,
            media_fit_mode VARCHAR(10) NOT NULL DEFAULT 'cover',
            slider_image_position VARCHAR(10) NOT NULL DEFAULT 'top',
            gallery_image_ids TEXT NULL,
            gallery_image_focus VARCHAR(15) NOT NULL DEFAULT '50,50',
            gallery_layout VARCHAR(20) NOT NULL DEFAULT 'grid',
            solo_layout VARCHAR(20) NOT NULL DEFAULT 'classic',
            right_block_title VARCHAR(191) NOT NULL DEFAULT '',
            right_block_text LONGTEXT NULL,
            right_block_title_font_family VARCHAR(120) NOT NULL DEFAULT '',
            right_block_title_font_size INT UNSIGNED NOT NULL DEFAULT 32,
            right_block_text_font_family VARCHAR(120) NOT NULL DEFAULT 'Inter, Arial, sans-serif',
            right_block_text_font_size INT UNSIGNED NOT NULL DEFAULT 24,
            right_block_font_family VARCHAR(120) NOT NULL DEFAULT '',
            right_block_font_size INT UNSIGNED NOT NULL DEFAULT 18,
            info_tooltip TEXT NULL,
            tooltip_size_ratio DECIMAL(4,2) NOT NULL DEFAULT 1.15,
            tooltip_text_size INT UNSIGNED NOT NULL DEFAULT 13,
            description_font_family VARCHAR(120) NOT NULL DEFAULT '',
            description_font_size INT UNSIGNED NOT NULL DEFAULT 18,
            duration_minutes INT UNSIGNED NOT NULL DEFAULT 60,
            show_duration_frontend TINYINT(1) NOT NULL DEFAULT 0,
            price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            discount_type VARCHAR(20) NOT NULL DEFAULT 'none',
            discount_value DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            campaign_note VARCHAR(255) NOT NULL DEFAULT '',
            dynamic_pricing_enabled TINYINT(1) NOT NULL DEFAULT 0,
            dynamic_weekend_percent DECIMAL(8,2) NOT NULL DEFAULT 0.00,
            dynamic_season_start DATE NULL,
            dynamic_season_end DATE NULL,
            dynamic_season_percent DECIMAL(8,2) NOT NULL DEFAULT 0.00,
            tax_enabled TINYINT(1) NOT NULL DEFAULT 0,
            tax_label VARCHAR(50) NOT NULL DEFAULT 'VAT',
            tax_rate DECIMAL(6,2) NOT NULL DEFAULT 0.00,
            tax_mode VARCHAR(20) NOT NULL DEFAULT 'exclusive',
            buffer_before INT UNSIGNED NOT NULL DEFAULT 0,
            buffer_after INT UNSIGNED NOT NULL DEFAULT 0,
            slot_step INT UNSIGNED NOT NULL DEFAULT 60,
            lead_time_minutes INT UNSIGNED NOT NULL DEFAULT 0,
            price_unit VARCHAR(20) NOT NULL DEFAULT 'fixed',
            hourly_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            checkin_time TIME NOT NULL DEFAULT '15:00:00',
            checkout_time TIME NOT NULL DEFAULT '11:00:00',
            min_nights INT UNSIGNED NOT NULL DEFAULT 1,
            max_nights INT UNSIGNED NOT NULL DEFAULT 30,
            inventory_units_json LONGTEXT NULL,
            date_inventory_json LONGTEXT NULL,
            date_flow VARCHAR(30) NOT NULL DEFAULT 'customer_choice',
            scheduled_events_json LONGTEXT NULL,
            included_services LONGTEXT NULL,
            extra_services_json LONGTEXT NULL,
            payment_policy VARCHAR(30) NOT NULL DEFAULT 'booking_only',
            deposit_type VARCHAR(20) NOT NULL DEFAULT 'percent',
            deposit_value DECIMAL(10,2) NOT NULL DEFAULT 30.00,
            booking_mode VARCHAR(20) NOT NULL DEFAULT 'fixed',
            mode_configs_json LONGTEXT NULL,
            checkout_mode VARCHAR(30) NOT NULL DEFAULT 'booking_only',
            hours_mode VARCHAR(20) NOT NULL DEFAULT 'global',
            open_247 TINYINT(1) NOT NULL DEFAULT 0,
            max_bookings_per_slot INT UNSIGNED NOT NULL DEFAULT 1,
            low_availability_notice_enabled TINYINT(1) NOT NULL DEFAULT 0,
            low_availability_threshold INT UNSIGNED NOT NULL DEFAULT 5,
            is_popular TINYINT(1) NOT NULL DEFAULT 0,
            popular_icon VARCHAR(20) NOT NULL DEFAULT '',
            popular_icon_color VARCHAR(20) NOT NULL DEFAULT '#7c3aed',
            popular_icon_size SMALLINT UNSIGNED NOT NULL DEFAULT 24,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            page_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY slug (slug),
            KEY category_id (category_id),
            KEY is_popular (is_popular),
            KEY is_active (is_active),
            KEY booking_mode (booking_mode),
            KEY checkout_mode (checkout_mode),
            KEY hours_mode (hours_mode),
            KEY open_247 (open_247),
            KEY page_id (page_id)
        ) {$charset};";
        $sql_events="CREATE TABLE {$events} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            package_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            title VARCHAR(191) NOT NULL,
            slug VARCHAR(191) NOT NULL,
            description LONGTEXT NULL,
            event_date DATE NOT NULL,
            end_date DATE NOT NULL,
            use_time TINYINT(1) NOT NULL DEFAULT 1,
            start_time TIME NOT NULL,
            end_time TIME NOT NULL,
            timezone VARCHAR(80) NOT NULL DEFAULT '',
            capacity INT UNSIGNED NOT NULL DEFAULT 1,
            booked_count INT UNSIGNED NOT NULL DEFAULT 0,
            price_override DECIMAL(10,2) NULL,
            discount_type VARCHAR(20) NOT NULL DEFAULT 'none',
            discount_value DECIMAL(10,2) NOT NULL DEFAULT 0,
            allow_coupons TINYINT(1) NOT NULL DEFAULT 1,
            payment_policy VARCHAR(30) NOT NULL DEFAULT 'booking_only',
            deposit_type VARCHAR(20) NOT NULL DEFAULT 'percent',
            deposit_value DECIMAL(10,2) NOT NULL DEFAULT 30.00,
            location VARCHAR(255) NOT NULL DEFAULT '',
            status VARCHAR(20) NOT NULL DEFAULT 'scheduled',
            reminder_profile VARCHAR(50) NOT NULL DEFAULT 'default',
            automation_profile VARCHAR(50) NOT NULL DEFAULT 'default',
            meta_json LONGTEXT NULL,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY slug (slug),
            KEY package_id (package_id),
            KEY event_date (event_date),
            KEY event_time (start_time,end_time),
            KEY status (status),
            KEY is_active (is_active),
            KEY package_date_status (package_id,event_date,status),
            KEY sltr_event_package_date_active (package_id,event_date,is_active,status)
        ) {$charset};";
        $sql_hours="CREATE TABLE {$hours} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            scope_type VARCHAR(20) NOT NULL DEFAULT 'global',
            scope_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            weekday TINYINT UNSIGNED NOT NULL,
            start_time TIME NOT NULL,
            end_time TIME NOT NULL,
            is_enabled TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY scope_lookup (scope_type, scope_id),
            KEY weekday (weekday),
            KEY is_enabled (is_enabled),
            KEY sltr_hours_scope_weekday_enabled (scope_type,scope_id,weekday,is_enabled)
        ) {$charset};";
        $sql_bookings="CREATE TABLE {$bookings} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            package_id BIGINT UNSIGNED NOT NULL,
            resource_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            staff_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            customer_name VARCHAR(191) NOT NULL,
            customer_email VARCHAR(191) NOT NULL,
            customer_phone VARCHAR(50) NULL,
            booking_locale VARCHAR(20) NOT NULL DEFAULT '',
            city VARCHAR(191) NULL,
            state VARCHAR(191) NULL,
            address VARCHAR(255) NULL,
            company VARCHAR(191) NULL,
            booking_date DATE NOT NULL,
            end_date DATE NULL,
            start_time TIME NOT NULL,
            end_time TIME NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'confirmed',
            payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid',
            payment_gateway VARCHAR(50) NOT NULL DEFAULT '',
            external_payment_id VARCHAR(191) NULL,
            payment_redirect_url TEXT NULL,
            paid_at DATETIME NULL,
            refunded_at DATETIME NULL,
            total_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            gross_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            amount_due_now DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            paid_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            remaining_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            deposit_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            extras_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            selected_extras_json LONGTEXT NULL,
            pricing_mode VARCHAR(20) NOT NULL DEFAULT 'fixed',
            payment_choice VARCHAR(30) NOT NULL DEFAULT '',
            payment_policy_snapshot_json LONGTEXT NULL,
            base_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            package_discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            pricing_adjustment_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            pricing_adjustment_label VARCHAR(255) NOT NULL DEFAULT '',
            coupon_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            coupon_code VARCHAR(50) NOT NULL DEFAULT '',
            coupon_discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            tax_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            coupon_usage_recorded TINYINT(1) NOT NULL DEFAULT 0,
            notes LONGTEXT NULL,
            source VARCHAR(50) NOT NULL DEFAULT 'frontend',
            cancellation_token VARCHAR(64) NULL,
            reschedule_token VARCHAR(64) NULL,
            active_slot_hash CHAR(64) NULL,
            cancelled_at DATETIME NULL,
            completed_at DATETIME NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY user_id (user_id),
            KEY package_id (package_id),
            KEY resource_id (resource_id),
            KEY staff_id (staff_id),
            KEY customer_email (customer_email),
            KEY booking_locale (booking_locale),
            KEY city (city),
            KEY state (state),
            KEY company (company),
            KEY booking_date (booking_date),
            KEY end_date (end_date),
            KEY booking_time (start_time),
            KEY end_time (end_time),
            KEY status (status),
            KEY payment_status (payment_status),
            KEY payment_gateway (payment_gateway),
            KEY external_payment_id (external_payment_id),
            UNIQUE KEY cancellation_token_unique (cancellation_token),
            UNIQUE KEY reschedule_token_unique (reschedule_token),
            UNIQUE KEY active_slot_hash_unique (active_slot_hash),
            KEY cancellation_token (cancellation_token),
            KEY reschedule_token (reschedule_token),
            KEY date_time_lookup (booking_date,start_time,end_time),
            KEY package_date_status (package_id,booking_date,status),
            KEY package_date_time_status (package_id,booking_date,start_time,end_time,status),
            KEY package_resource_date_status (package_id,resource_id,booking_date,status),
            KEY package_staff_date_status (package_id,staff_id,booking_date,status),
            KEY customer_email_status (customer_email,status),
            KEY coupon_usage_recorded (coupon_usage_recorded),
            KEY payment_status_gateway (payment_status,payment_gateway),
            KEY sltr_booking_date_status_time (booking_date,status,start_time),
            KEY sltr_booking_status_date_time (status,booking_date,start_time),
            KEY sltr_booking_package_inventory_day (package_id,resource_id,staff_id,booking_date,status),
            KEY sltr_booking_resource_day_time (resource_id,booking_date,start_time,end_time,status),
            KEY sltr_booking_staff_day_time (staff_id,booking_date,start_time,end_time,status),
            KEY sltr_booking_customer_date (customer_email,booking_date),
            KEY sltr_booking_completed_marketing (status,completed_at,booking_date)
        ) {$charset};";
        $sql_log="CREATE TABLE {$log} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            object_type VARCHAR(50) NOT NULL,
            object_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            event VARCHAR(100) NOT NULL,
            actor_type VARCHAR(50) NOT NULL DEFAULT 'system',
            actor_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            status VARCHAR(20) NOT NULL DEFAULT 'info',
            gateway VARCHAR(50) NOT NULL DEFAULT '',
            message TEXT NULL,
            error_message TEXT NULL,
            payload_json LONGTEXT NULL,
            ip_address VARCHAR(100) NULL,
            user_agent VARCHAR(255) NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY object_lookup (object_type,object_id),
            KEY event (event),
            KEY status (status),
            KEY gateway (gateway),
            KEY created_at (created_at),
            KEY sltr_activity_object_created (object_type,object_id,created_at),
            KEY sltr_activity_event_created (event,created_at),
            KEY sltr_activity_status_created (status,created_at)
        ) {$charset};";
        $sql_history="CREATE TABLE {$history} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            booking_id BIGINT UNSIGNED NOT NULL,
            event VARCHAR(100) NOT NULL,
            old_status VARCHAR(20) NULL,
            new_status VARCHAR(20) NULL,
            old_payment_status VARCHAR(20) NULL,
            new_payment_status VARCHAR(20) NULL,
            actor_type VARCHAR(50) NOT NULL DEFAULT 'system',
            actor_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            message TEXT NULL,
            payload_json LONGTEXT NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY booking_id (booking_id),
            KEY event (event),
            KEY created_at (created_at),
            KEY sltr_history_booking_created (booking_id,created_at),
            KEY sltr_history_event_created (event,created_at)
        ) {$charset};";
        $sql_coupons="CREATE TABLE {$coupons} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            code VARCHAR(50) NOT NULL,
            description TEXT NULL,
            discount_type VARCHAR(20) NOT NULL DEFAULT 'percent',
            discount_value DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            usage_limit INT UNSIGNED NOT NULL DEFAULT 0,
            usage_limit_per_email INT UNSIGNED NOT NULL DEFAULT 0,
            used_count INT UNSIGNED NOT NULL DEFAULT 0,
            expires_at DATE NULL,
            package_ids TEXT NULL,
            min_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY code (code),
            KEY is_active (is_active),
            KEY expires_at (expires_at),
            KEY sltr_coupon_active_expires (is_active,expires_at)
        ) {$charset};";
        $sql_marketing_campaigns="CREATE TABLE {$marketing_campaigns} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            name VARCHAR(191) NOT NULL,
            template_key VARCHAR(100) NOT NULL DEFAULT '',
            subject_override TEXT NULL,
            audience_type VARCHAR(40) NOT NULL DEFAULT 'all',
            package_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            coupon_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            generate_unique_coupons TINYINT(1) NOT NULL DEFAULT 0,
            cta_enabled TINYINT(1) NOT NULL DEFAULT 1,
            cta_label VARCHAR(120) NOT NULL DEFAULT '',
            cta_url_type VARCHAR(30) NOT NULL DEFAULT 'booking',
            cta_custom_url TEXT NULL,
            audience_statuses TEXT NULL,
            audience_payment_statuses TEXT NULL,
            audience_last_booking_mode VARCHAR(30) NOT NULL DEFAULT 'any',
            audience_last_booking_days INT UNSIGNED NOT NULL DEFAULT 30,
            audience_min_bookings INT UNSIGNED NOT NULL DEFAULT 0,
            audience_max_bookings INT UNSIGNED NOT NULL DEFAULT 0,
            audience_min_spent DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            audience_max_spent DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            audience_coupon_filter VARCHAR(30) NOT NULL DEFAULT 'any',
            marketing_headline VARCHAR(255) NOT NULL DEFAULT '',
            marketing_message TEXT NULL,
            marketing_submessage TEXT NULL,
            source VARCHAR(20) NOT NULL DEFAULT 'coupon',
            automation_type VARCHAR(30) NOT NULL DEFAULT '',
            status VARCHAR(20) NOT NULL DEFAULT 'draft',
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY template_key (template_key),
            KEY audience_type (audience_type),
            KEY package_id (package_id),
            KEY coupon_id (coupon_id),
            KEY generate_unique_coupons (generate_unique_coupons),
            KEY cta_enabled (cta_enabled),
            KEY audience_last_booking_mode (audience_last_booking_mode),
            KEY audience_coupon_filter (audience_coupon_filter),
            KEY source (source),
            KEY automation_type (automation_type),
            KEY status (status),
            KEY created_at (created_at)
        ) {$charset};";
        $sql_marketing_logs="CREATE TABLE {$marketing_logs} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            campaign_id BIGINT UNSIGNED NOT NULL,
            customer_email VARCHAR(191) NOT NULL,
            customer_name VARCHAR(191) NOT NULL DEFAULT '',
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            subject TEXT NULL,
            error_message TEXT NULL,
            sent_at DATETIME NULL,
            attempts INT UNSIGNED NOT NULL DEFAULT 0,
            max_attempts INT UNSIGNED NOT NULL DEFAULT 3,
            last_try DATETIME NULL,
            payload_json LONGTEXT NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY campaign_email (campaign_id,customer_email),
            KEY campaign_id (campaign_id),
            KEY customer_email (customer_email),
            KEY status (status),
            KEY attempts (attempts),
            KEY last_try (last_try),
            KEY sent_at (sent_at),
            KEY created_at (created_at)
        ) {$charset};"
;
        $sql_webhooks="CREATE TABLE {$webhooks} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            gateway VARCHAR(50) NOT NULL DEFAULT '',
            event_id VARCHAR(191) NULL,
            fingerprint CHAR(64) NOT NULL,
            booking_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            status VARCHAR(20) NOT NULL DEFAULT 'received',
            payload_json LONGTEXT NULL,
            error_message TEXT NULL,
            processed_at DATETIME NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY event_id (event_id),
            UNIQUE KEY fingerprint (fingerprint),
            KEY gateway (gateway),
            KEY booking_id (booking_id),
            KEY status (status),
            KEY created_at (created_at)
        ) {$charset};";
        $sql_email_queue="CREATE TABLE {$email_queue} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            booking_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            scenario VARCHAR(100) NOT NULL,
            recipient_type VARCHAR(50) NOT NULL DEFAULT 'customer',
            recipient_email VARCHAR(191) NOT NULL,
            subject TEXT NULL,
            body LONGTEXT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            attempts INT UNSIGNED NOT NULL DEFAULT 0,
            max_attempts INT UNSIGNED NOT NULL DEFAULT 3,
            send_at DATETIME NOT NULL,
            sent_at DATETIME NULL,
            last_error TEXT NULL,
            payload_json LONGTEXT NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY booking_id (booking_id),
            KEY scenario (scenario),
            KEY recipient_email (recipient_email),
            KEY status (status),
            KEY send_at (send_at),
            KEY due_lookup (status,send_at),
            KEY booking_scenario (booking_id,scenario,recipient_type)
        ) {$charset};";

        $sql_outgoing_endpoints="CREATE TABLE {$outgoing_endpoints} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            name VARCHAR(191) NOT NULL DEFAULT '',
            url TEXT NOT NULL,
            secret VARCHAR(128) NOT NULL DEFAULT '',
            events TEXT NULL,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY is_active (is_active),
            KEY created_at (created_at)
        ) {$charset};";
        $sql_rate_limits="CREATE TABLE {$rate_limits} (
            namespace VARCHAR(64) NOT NULL,
            identity_hash CHAR(32) NOT NULL,
            bucket BIGINT UNSIGNED NOT NULL,
            attempts INT UNSIGNED NOT NULL DEFAULT 0,
            expires_at INT UNSIGNED NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (namespace, identity_hash, bucket),
            KEY expires_at (expires_at),
            KEY namespace_expires (namespace, expires_at)
        ) {$charset};";
        $sql_rest_hmac_nonces="CREATE TABLE {$rest_hmac_nonces} (
            nonce_hash CHAR(64) NOT NULL,
            api_key_hash CHAR(64) NOT NULL,
            request_timestamp INT UNSIGNED NOT NULL,
            expires_at INT UNSIGNED NOT NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (nonce_hash),
            KEY api_key_hash (api_key_hash),
            KEY expires_at (expires_at)
        ) {$charset};";
        $sql_visitor_events="CREATE TABLE {$visitor_events} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            session_hash CHAR(64) NOT NULL,
            ip_prefix_hash CHAR(64) NOT NULL DEFAULT '',
            city VARCHAR(191) NOT NULL DEFAULT 'Unknown city',
            country VARCHAR(80) NOT NULL DEFAULT '',
            page_url TEXT NOT NULL,
            page_title VARCHAR(255) NOT NULL DEFAULT '',
            page_type VARCHAR(40) NOT NULL DEFAULT 'page',
            package_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            post_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            referrer TEXT NULL,
            utm_source VARCHAR(100) NOT NULL DEFAULT '',
            utm_medium VARCHAR(100) NOT NULL DEFAULT '',
            utm_campaign VARCHAR(150) NOT NULL DEFAULT '',
            duration_seconds INT UNSIGNED NOT NULL DEFAULT 0,
            viewport_events INT UNSIGNED NOT NULL DEFAULT 0,
            booking_started TINYINT(1) NOT NULL DEFAULT 0,
            booking_created TINYINT(1) NOT NULL DEFAULT 0,
            bounced TINYINT(1) NOT NULL DEFAULT 0,
            exited TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY created_at (created_at),
            KEY page_type_created (page_type,created_at),
            KEY package_created (package_id,created_at),
            KEY post_created (post_id,created_at),
            KEY city_created (city,created_at),
            KEY session_created (session_hash,created_at),
            KEY ip_prefix_created (ip_prefix_hash,created_at),
            KEY booking_created_idx (booking_created,created_at),
            KEY bounced_created (bounced,created_at)
        ) {$charset};";

        $sql_outgoing_deliveries="CREATE TABLE {$outgoing_deliveries} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            endpoint_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            event VARCHAR(100) NOT NULL DEFAULT '',
            event_id VARCHAR(64) NOT NULL DEFAULT '',
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            attempts INT UNSIGNED NOT NULL DEFAULT 0,
            max_attempts INT UNSIGNED NOT NULL DEFAULT 5,
            next_attempt_at DATETIME NULL,
            delivered_at DATETIME NULL,
            http_code INT UNSIGNED NOT NULL DEFAULT 0,
            response_body LONGTEXT NULL,
            error_message TEXT NULL,
            payload_json LONGTEXT NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY event_endpoint (event_id,endpoint_id),
            KEY endpoint_id (endpoint_id),
            KEY event (event),
            KEY status (status),
            KEY next_attempt_at (next_attempt_at),
            KEY created_at (created_at)
        ) {$charset};";

        $sql_payment_transactions="CREATE TABLE {$payment_transactions} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            booking_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            customer_email VARCHAR(191) NOT NULL DEFAULT '',
            gateway VARCHAR(50) NOT NULL DEFAULT '',
            transaction_type VARCHAR(30) NOT NULL DEFAULT 'payment',
            status VARCHAR(30) NOT NULL DEFAULT 'pending',
            amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            currency VARCHAR(10) NOT NULL DEFAULT 'EUR',
            external_id VARCHAR(191) NOT NULL DEFAULT '',
            external_parent_id VARCHAR(191) NOT NULL DEFAULT '',
            mode VARCHAR(20) NOT NULL DEFAULT 'test',
            description TEXT NULL,
            error_message TEXT NULL,
            metadata_json LONGTEXT NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY booking_id (booking_id),
            KEY customer_email (customer_email),
            KEY gateway (gateway),
            KEY status (status),
            KEY transaction_type (transaction_type),
            KEY external_id (external_id),
            KEY gateway_external (gateway,external_id),
            KEY created_at (created_at),
            KEY sltr_payment_status_created (status,created_at),
            KEY sltr_payment_booking_created (booking_id,created_at)
        ) {$charset};";


        $sql_payment_invoices="CREATE TABLE {$payment_invoices} (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            invoice_number VARCHAR(64) NOT NULL DEFAULT '',
            booking_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
            customer_email VARCHAR(191) NOT NULL DEFAULT '',
            customer_name VARCHAR(191) NOT NULL DEFAULT '',
            status VARCHAR(30) NOT NULL DEFAULT 'draft',
            currency VARCHAR(10) NOT NULL DEFAULT 'EUR',
            subtotal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            tax_label VARCHAR(50) NOT NULL DEFAULT 'VAT',
            tax_rate DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
            tax_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            paid DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            remaining DECIMAL(10,2) NOT NULL DEFAULT 0.00,
            issue_date DATE NULL,
            due_date DATE NULL,
            notes TEXT NULL,
            metadata_json LONGTEXT NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY invoice_number (invoice_number),
            KEY booking_id (booking_id),
            KEY customer_email (customer_email),
            KEY status (status),
            KEY created_at (created_at)
        ) {$charset};";

        $schema_steps = [
            'categories' => $sql_categories,
            'locations' => $sql_locations,
            'package_locations' => $sql_package_locations,
            'packages' => $sql_packages,
            'events' => $sql_events,
            'working_hours' => $sql_hours,
            'bookings' => $sql_bookings,
            'activity_log' => $sql_log,
            'booking_history' => $sql_history,
            'coupons' => $sql_coupons,
            'marketing_campaigns' => $sql_marketing_campaigns,
            'marketing_logs' => $sql_marketing_logs,
            'rate_limits' => $sql_rate_limits,
            'rest_hmac_nonces' => $sql_rest_hmac_nonces,
            'visitor_events' => $sql_visitor_events,
            'webhook_events' => $sql_webhooks,
            'email_queue' => $sql_email_queue,
            'outgoing_webhook_endpoints' => $sql_outgoing_endpoints,
            'outgoing_webhook_deliveries' => $sql_outgoing_deliveries,
            'payment_transactions' => $sql_payment_transactions,
            'payment_invoices' => $sql_payment_invoices,
        ];

        foreach ($schema_steps as $sql) {
            dbDelta($sql);
        }
    }
}
